<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Caption' => 'Caption',
    'Created At' => 'Created At',
    'Created By' => 'Created By',
    'Extension' => 'Extension',
    'File Path' => 'File Path',
    'File Size' => 'File Size',
    'Filter Identifier' => 'Filter Identifier',
    'Folder ID' => 'Folder ID',
    'Hash File' => 'Hash File',
    'Hash Name' => 'Hash Name',
    'ID' => 'ID',
    'Inline Disposition' => 'Inline Disposition',
    'Is Deleted' => 'Is Deleted',
    'Is Hidden' => 'Is Hidden',
    'Is Visibility' => 'Is Visibility',
    'Mime Type' => 'Mime Type',
    'Name New' => 'Name New',
    'Name New Compound' => 'Name New Compound',
    'Name Original' => 'Name Original',
    'Parent ID' => 'Parent ID',
    'Path Prefix' => 'Path Prefix',
    'Resolution Height' => 'Resolution Height',
    'Resolution Width' => 'Resolution Width',
    'Updated At' => 'Updated At',
    'Updated By' => 'Updated By',
];
