<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'api_storage_file_upload_folder_error' => 'Error while saving the file in the storage folder. A permission error could cause this problem. Make sure the storage folder is writable.',
    'api_storage_file_upload_success' => 'Files have been uploaded successfully.',
    'upload_err_message_0' => 'There is no error, the file uploaded with success.',
    'upload_err_message_1' => 'The uploaded file exceeds the upload_max_filesize directive in php.ini.',
    'upload_err_message_2' => 'The uploaded file exceeds the MAX_FILE_SIZE directive that was specified in the HTML form.',
    'upload_err_message_3' => 'The uploaded file was only partially uploaded.',
    'upload_err_message_4' => 'No file was uploaded.',
    'upload_err_message_6' => 'Missing a temporary folder.',
    'upload_err_message_7' => 'Failed to write file to disk.',
    'upload_err_message_8' => 'A PHP extension stopped the file upload.',
    'api_storage_not_found' => 'storageKey not found',
];
