<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'api_storage_file_upload_folder_error' => 'Dosyayı depolama klasöründe kaydederken hata oluştu. Bir izin hatası bu soruna neden olabilir. Depolama klasörünün yazılabilir olduğundan emin olun.',
    'api_storage_file_upload_success' => 'Dosyalar başarıyla yüklendi.',
    'upload_err_message_0' => 'Dosya hatasız bir şekilde yüklendi.',
    'upload_err_message_1' => 'Yüklenen dosya, php.ini dosyasındaki upload_max_filesize yönergesini aşıyor.',
    'upload_err_message_2' => 'Yüklenen dosya, HTML biçiminde belirtilen MAX_FILE_SIZE yönergesini aşıyor.',
    'upload_err_message_3' => 'Yüklenen dosya kısmi olarak yüklendi.',
    'upload_err_message_4' => 'Hiçbir dosya yüklenmedi.',
    'upload_err_message_6' => 'Geçici klasör eksik.',
    'upload_err_message_7' => 'Dosya diske yazılamadı.',
    'upload_err_message_8' => 'Bir PHP uzantısı dosya yükleme işlemini durdurdu.',
    'api_storage_not_found' => 'storageKey bulunamadı.',
];
