<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Caption' => 'Başlık',
    'Created At' => 'Oluşturma Zamanı',
    'Created By' => 'Oluşturan',
    'Extension' => 'Uzantı',
    'File Path' => 'Dosya Yolu',
    'File Size' => 'Dosya Boyutu',
    'Filter Identifier' => 'Filtre',
    'Folder ID' => 'Klasör',
    'Hash File' => 'Hash',
    'Hash Name' => 'Hash Name',
    'ID' => 'ID',
    'Inline Disposition' => 'Tarayıcıda Göster',
    'Is Deleted' => 'Silindi mi?',
    'Is Hidden' => 'Gizli mi?',
    'Is Visibility' => 'Görüntülenebilir mi?',
    'Mime Type' => 'Dosya Türü',
    'Name New' => 'Yeni Dosya Adı',
    'Name New Compound' => 'Yeni Dosya Adı',
    'Name Original' => 'Orjinal Dosya Adı',
    'Parent ID' => 'Parent ID',
    'Path Prefix' => 'Path Prefix',
    'Resolution Height' => 'Yükseklik',
    'Resolution Width' => 'Genişlik',
    'Updated At' => 'Güncelleme Zamanı',
    'Updated By' => 'Güncelleyen',
];
